#!/usr/bin/env python3
"""Create the browser-safe Supabase config used by the public Pages build."""

from __future__ import annotations

import json
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = Path(
    os.environ.get(
        "HOMEALACARTE_CONFIG_OUTPUT",
        ROOT / "www" / "supabase-config.js",
    )
).resolve()


def required_environment(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(
            f"Missing GitHub repository setting: {name}. "
            "Public deployment stopped before producing an offline-only site."
        )
    return value


config = {
    "projectUrl": required_environment("SUPABASE_PROJECT_URL").rstrip("/"),
    "publishableKey": required_environment("SUPABASE_PUBLISHABLE_KEY"),
    "controllerName": "Bruno Bodin",
    "privacyContact": "https://github.com/bbodin",
    "lawfulBasis": (
        "GDPR Art. 6(1)(b); Art. 9(2)(a) where entered data reveals "
        "health information"
    ),
    "retentionPolicy": (
        "One year after last activity; one week for empty accounts; "
        "user-requested deletion is completed within seven days"
    ),
}

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(
    "// Generated by scripts/write_supabase_config.py; do not commit this file.\n"
    f"export const SUPABASE_CONFIG = {json.dumps(config, indent=2)};\n",
    encoding="utf-8",
)
try:
    displayed_output = OUTPUT.relative_to(ROOT)
except ValueError:
    displayed_output = OUTPUT
print(f"Created browser-safe configuration at {displayed_output}.")
